CREATE TABLE EN_TRLOG
(
  TRTIMESTAMP CHAR(17) DEFAULT '00000000000000000'  NOT NULL
  ,
  TRDATE      CHAR(8) DEFAULT '00000000'            NOT NULL
  ,
  TRTIME      CHAR(9) DEFAULT '000000000'           NOT NULL
  ,
  SYSCODE     VARCHAR(20) DEFAULT ' '               NOT NULL
  ,
  ORGCODE     VARCHAR2(20) DEFAULT ' '              NOT NULL
  ,
  DESTINATION VARCHAR2(20) DEFAULT ' '              NOT NULL
  ,
  SOURCE      VARCHAR2(20) DEFAULT ' '              NOT NULL
  ,
  TRNO        VARCHAR2(50) DEFAULT ' '              NOT NULL
  ,
  RQGB        CHAR(1) DEFAULT ' '                   NOT NULL
  ,
  SRGB        CHAR(1) DEFAULT ' '                   NOT NULL
  ,
  MSGCODE     VARCHAR2(200) DEFAULT ' '             NOT NULL
  ,
  TXCD        VARCHAR2(10) DEFAULT ' '              NOT NULL
  ,
  TRCD        VARCHAR2(10) DEFAULT ' '              NOT NULL
  ,
  RESPCD      VARCHAR2(10) DEFAULT ' '              NOT NULL
  ,
  TRACENO     VARCHAR2(20) DEFAULT ' '              NOT NULL
  ,
  USERDATA    VARCHAR2(40) DEFAULT ' '              NOT NULL
  ,
  INLEN       NUMBER(10) DEFAULT 0                  NOT NULL
  ,
  ETIME       NUMBER(10) DEFAULT 0                  NOT NULL
  ,
  RTIME       NUMBER(10) DEFAULT 0                  NOT NULL
  ,
  TXLEN       NUMBER(10) DEFAULT 0                  NOT NULL
  ,
  TXCOUNT     NUMBER(10) DEFAULT 0                  NOT NULL
  ,
  COMPRESS_YN CHAR(1) DEFAULT 'N'                   NOT NULL
  ,
  ETC1        VARCHAR2(60) DEFAULT ' '              NOT NULL
  ,
  ETC2        VARCHAR2(60) DEFAULT ' '              NOT NULL
  ,
  ETC3        VARCHAR2(60) DEFAULT ' '              NOT NULL
);

CREATE INDEX EN_TRLOG_I1
  ON EN_TRLOG (TRTIMESTAMP DESC, TRNO);

CREATE TABLE EN_TRLOG_MESG
(
  TRTIMESTAMP CHAR(17) DEFAULT '00000000000000000'  NOT NULL
  ,
  SYSCODE     VARCHAR(10) DEFAULT ' '               NOT NULL
  ,
  ORGCODE     VARCHAR(20) DEFAULT ' '               NOT NULL
  ,
  DESTINATION VARCHAR2(10) DEFAULT ' '              NOT NULL
  ,
  SOURCE      VARCHAR2(10) DEFAULT ' '              NOT NULL
  ,
  TRNO        VARCHAR2(20) DEFAULT ' '              NOT NULL
  ,
  RQGB        CHAR(1) DEFAULT ' '                   NOT NULL
  ,
  SRGB        CHAR(1) DEFAULT ' '                   NOT NULL
  ,
  TXSEQ       NUMBER(10) DEFAULT 0                  NOT NULL
  ,
  TXDATA      VARCHAR2(4000) DEFAULT ' '            NOT NULL
);

CREATE INDEX EN_TRLOG_MESG_I1
  ON EN_TRLOG_MESG (TRTIMESTAMP DESC, TRNO);

SELECT
  T.TRTIMESTAMP AS TRTIMESTAMP,
  T.SYSCODE     AS SYSCODE,
  T.ORGCODE     AS ORGCODE,
  T.DESTINATION AS DESTINATION,
  T.SOURCE      AS SOURCE,
  T.TRNO        AS TRNO,
  T.RQGB        AS RQGB,
  T.SRGB        AS SRGB,
  T.MSGCODE     AS MSGCODE,
  T.TXCD        AS TXCD,
  T.TRCD        AS TRCD,
  T.RESPCD      AS RESPCD,
  T.TRACENO     AS TRACENO,
  T.USERDATA    AS USERDATA,
  T.ETC1        AS ETC1,
  T.ETC2        AS ETC2,
  T.ETC3        AS ETC3,
  T.INLEN       AS INLEN,
  T.ETIME       AS ETIME,
  T.RTIME       AS RTIME,
  T.TXLEN       AS TXLEN,
  T.COMPRESS_YN AS COMPRESS_YN,
  T.TXCOUNT     AS TXCOUNT,
  M.TXSEQ       AS TXSEQ,
  M.TXDATA      AS TXDATA
FROM EN_TRLOG T LEFT OUTER JOIN EN_TRLOG_MESG M
    ON T.SYSCODE = M.SYSCODE AND T.TRTIMESTAMP = M.TRTIMESTAMP AND T.TRNO = M.TRNO AND T.ORGCODE = M.ORGCODE
       AND T.DESTINATION = M.DESTINATION AND T.SOURCE = M.SOURCE AND T.RQGB = M.RQGB AND T.SRGB = M.SRGB;

CREATE TABLE IS_USER
(
  USER_ID     VARCHAR2(20) NOT NULL PRIMARY KEY ,
  USER_PW     VARCHAR2(20) DEFAULT 'malife#2' NOT NULL,
  USER_NM     VARCHAR2(20) NOT NULL,
  AUTH_CD     VARCHAR2(6) DEFAULT '0' NOT NULL,
  ORGNM       VARCHAR2(30),
  USE_YN      VARCHAR2(1) DEFAULT 'Y',
  LOGIN_TIME   DATE,
  LOGOUT_TIME  DATE,
  FILLER1      VARCHAR2(30),
  FILLER2      VARCHAR2(30),
  FILLER3      VARCHAR2(30),
  IPDTM    DATE NOT NULL
);
-- drop TABLE IS_USER;
--
--
-- insert into IS_USER
-- values ('00124114','malife#2','박재영','9','IT운영팀','Y',sysdate,sysdate,'','','',sysdate);
--
-- COMMIT;
-- insert into IS_USER
-- values ('test','test','홍길동','5','개발','Y',sysdate,sysdate,'','','',sysdate);